[package]
name = "hitting-sets"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = ["highs"]
highs = ["dep:highs"]
gurobi9 = ["dep:grb", "grb/gurobi9"]
gurobi12 = ["dep:grb", "grb/gurobi12"]

[dependencies]
cpu-time.workspace = true
grb = { workspace = true, optional = true }
highs = { workspace = true, optional = true }
rustsat.workspace = true
thiserror.workspace = true
