[package]
name = "scuttle-proc"
authors.workspace = true
license.workspace = true
description = "Procedural macros for scuttle. This crate is not intended to be used outside of scuttle."
keywords = ["solver", "multi-objective", "maxsat"]
repository = "https://github.com/chrjabs/scuttle"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "2.0.72"
quote = "1.0.36"
darling = "0.20.10"

[features]
interrupt-oracle = []
phasing = []
sol-tightening = []
limit-conflicts = []
